on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Add untracked file
      run: |
        # this is a processed file, like a composer vendor folder or npm build folder
        touch an-untracked-file.php
    - name: Insert .wpcom-ignore file
      run: |
        # this will be passed as an argument to the LFTP client when transferring files
        echo package.json > .wpcom-ignore
    - name: Deploy files via SFTP
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: sftp
        remote-host: sftp.wp.com
        remote-user: ${{ secrets.FTP_USER }}
        remote-password: ${{ secrets.FTP_PASSWORD }}
        remote-path: /htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }}
        sync: full # support untracked files
        ftp-mirror-options: --exclude-glob-from=.wpcom-ignore # do not transfer these files
        ftp-post-sync-commands: |
          # remove the .wpcom-ignore file from remote
          rm /htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }}/.wpcom-ignore
    - name: Link the files in htdocs and remove old references
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: sftp.wp.com
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 22
        script: |
          # symlink the contents of current version into htdocs
          cp -Rsf /htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }}/* /htdocs
          # removes older copies from working area
          cd /htdocs/working-area/${{ github.event.repository.name }}
          find . ! -path './${{ github.sha }}*' -delete
          # removes broken symlinks
          find /srv/htdocs -xtype l -delete
