on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add untracked file
      run: |
        # this is a processed file, like a composer vendor folder or npm build folder
        touch an-untracked-file.php
    - name: Ignore some files
      run: |
        echo \*.git\* >> .wpcom-ignore
        echo .wpcom-ignore >> .wpcom-ignore
    - uses: montudor/action-zip@v1
      with:
        args: zip -r artifact.zip . --exclude @.wpcom-ignore
    - uses: actions/upload-artifact@v4
      id: artifact-upload-step
      with:
        name: my-artifact
        path: artifact.zip
    - name: Output artifact URL
      run:  echo 'Artifact URL is ${{ steps.artifact-upload-step.outputs.artifact-url }}'
    - uses: joutvhu/delete-artifact@v2
      with:
        name: my-artifact
    # - uses: actions/upload-artifact@v4
    #   with:
    #     name: artifact.zip
    #     path: artifact.zip
    # - name: Upload to WordPress.com
    #   uses: fjogeleit/http-request-action@v1
    #   with:
    #     url: https://public-api.wordpress.com/wpcom/v2/code-deployment
    #     method: POST
    #     file: artifact.zip
    #     customHeaders: '{"X-WPCOM-Connection-Token":"${{ secrets.WPCOM_CONNECTION_TOKEN }}"}'
