on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Add untracked file
      run: |
        touch a-new-file.php
    - name: Deploy files via SFTP
      uses: milanmk/actions-file-deployer@master
      with:
        remote-protocol: "sftp"
        remote-host: sftp.wp.com
        remote-user: ${{ secrets.FTP_USER }}
        remote-password: ${{ secrets.FTP_PASSWORD }}
        remote-path: /htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }}
        sync: full # support untracked files
        ftp-post-sync-commands: |
          cp -Rsf /srv/htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }}/* /srv/htdocs
          rm -rf /srv/htdocs/working-area/${{ github.event.repository.name }}/!(${{ github.sha }})
          find /srv/htdocs/ -xtype l -delete
