on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Add untracked file
      run: |
        # this is a processed file, like a composer vendor folder or npm build folder
        touch an-untracked-file.php
    - name: Insert .wpcom-ignore file
      run: |
        # this will be passed as an argument to the LFTP client when transferring files
        echo package.json > .wpcom-ignore
    - uses: actions/upload-artifact@v4
      with:
        name: wpcom-deployment-${{ github.event.repository.name }}/${{ github.sha }}
    # - name: Link the files in htdocs and remove old references
    #   uses: appleboy/ssh-action@v1.0.3
    #   with:
    #     host: sftp.wp.com
    #     username: ${{ secrets.FTP_USER }}
    #     password: ${{ secrets.FTP_PASSWORD }}
    #     port: 22
    #     script: |
    #       # symlink the contents of current version into htdocs
    #       cp -RsfT /srv/htdocs/working-area/${{ github.event.repository.name }}/${{ github.sha }} /srv/htdocs
    #       # removes older copies from working area
    #       cd /srv/htdocs/working-area/${{ github.event.repository.name }}
    #       find . ! -path './${{ github.sha }}*' -delete
    #       # removes broken symlinks for that repos working area
    #       find /srv/htdocs -xtype l -lname '/srv/htdocs/working-area/${{ github.event.repository.name }}/*' -delete
