name: Publish Website
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: true
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: actions/upload-artifact@v4
      with:
        name: my-artifact
        path: artifact.zip
