on: push
name: Publish Website
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 2
    - name: Add untracked file
      run: |
        touch untracked-file-probably-composer-vendor.php
    - name: Store files from repo
      run: |
        find . -mindepth 1 -not -path "./.git*" > .git-ftp-files.log
        echo !.git-ftp-files.log > .git-ftp-include
    - name: FTP-Deploy-Action
      uses: Automattic/FTP-Deploy-Action@3.1.2
      with:
        ftp-server: sftp://sftp.wp.com/htdocs/
        ftp-username: ${{ secrets.FTP_USER }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
